### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by LogGits** [mcgrizzz/ProtonExamples#2]
So I have been looking into testing this but i need some info;

**_What is the purpose of using `(this, this)` and could it just be done as `(this)`?_**
https://github.com/mcgrizzz/ProtonExamples/blob/46bb47d94502c032d0b5f3d09527a75a518cdbe9/src/main/java/me/drepic/protonexamples/networkchat/NetworkChat.java#L17

**_What do the namespace & subject mean and what is the intended usecase for both?_**
https://github.com/mcgrizzz/ProtonExamples/blob/46bb47d94502c032d0b5f3d09527a75a518cdbe9/src/main/java/me/drepic/protonexamples/networkchat/NetworkChat.java#L30-L33

**_Could I use this to have bungee and spigot communicate via this scenario:_**
- spigot players message gets sent to bungee (to check for cancelling)
- bungee extracts info and parses data

**_^ if so, how would i setup something like this? would it be like:_**
- manager on spigot and bungee
- getSyncManager.broadcast() ? **_<- no sure if there is another one_**
then this in the bungee plugin (**_if so, would i need a PlayerMessage object in the bungee plugin aswell and would it need the same args or can it be different?_**):
```java
@MessageHandler(namespace = "networkchat", subject="chatMessage")
public void onChatReceived(PlayerMessage message){
    getServer().broadcastMessage(String.format("<%s> %s", message.getPlayer(), message.getMessage()));
}
```
By different PlayerMessage args I mean could I use this:
```java
public PlayerMessage (Player player, String message) {
    this.player = player.getDisplayName();
    this.uuid = player.getUniqueId().toString();
    this.message = message;
}
```

Thanks in advance :)

**Comment by mcgrizzz** [comment]
> **_What is the purpose of using `(this, this)` and could it just be done as `(this)`?_**
> https://github.com/mcgrizzz/ProtonExamples/blob/46bb47d94502c032d0b5f3d09527a75a518cdbe9/src/main/java/me/drepic/protonexamples/networkchat/NetworkChat.java#L17

I realized I haven't updated to the latest Proton version for this repository. It should be fixed in the latest commit. Before the current version, Proton needed a reference to your plugin (hence this, this). 
 
> **_What do the namespace & subject mean and what is the intended usecase for both?_**
> https://github.com/mcgrizzz/ProtonExamples/blob/46bb47d94502c032d0b5f3d09527a75a518cdbe9/src/main/java/me/drepic/protonexamples/networkchat/NetworkChat.java#L30-L33

Namespace and Subject essentially define the datatype you want to send and receive. 

In the example you showed, if you send an `integer` to `namespace = "networkchat", subject="chatMessage"`, Proton will throw an error because it is expecting a `PlayerMessage`. 

In broad terms, namespace should refer to your plugin itself or your organization. Subject should be specific to the type of message your sending and receiving.

You can read more here: https://proton-1.gitbook.io/proton/getting-started#sending-your-first-message

> **_Could I use this to have bungee and spigot communicate via this scenario:_**
> 
> * spigot players message gets sent to bungee (to check for cancelling)
> * bungee extracts info and parses data

You can. However, you only really need a copy of Proton running on bungee if you need access to the proxy. Otherwise, you can just communicate between all the spigot servers the same way. 

Here's an example of where I used Proton on both Spigot and Bungee: https://github.com/mcgrizzz/DynamicProxy/tree/main/src/main/java/me/drepic/dynamicproxy
https://www.spigotmc.org/resources/dynamicproxy.88566/

> **_^ if so, how would i setup something like this? would it be like:_**
> 
> * manager on spigot and bungee

Look at DynamicProxy link above as example for use on spigot and bungee. 

> * getSyncManager.broadcast() ? **_<- no sure if there is another one_**

I'm not sure what getSyncManager is referring to here. 

>   then this in the bungee plugin (**_if so, would i need a PlayerMessage object in the bungee plugin aswell and would it need the same args or can it be different?_**):

If you send a `PlayerMessage` from the spigot side, the bungeeside will try to parse into whatever parameter you provide.

Example:

Spigot Server:

- Sends `PlayerMessage` to bungee proxy @ (namespace = "test", subject="message")

Bungee Proxy

- Listens for an `integer` @ (namespace = "test", subject="message)

In this case, you will get an error when bungee receives a message because the datatypes do not match and Proton does not know how to convert a `PlayerMessage` into an `integer`.

The same idea applies even if you have the same class name, but a different class constructor.

 It will throw an error if the `PlayerMessage` defined is different than the one received. So you will need to define it in both plugins. 

NOTE: Proton can send most datatypes. 

> Thanks in advance :)

For more detail, you can generally find it on the documentation page: https://proton-1.gitbook.io/proton/getting-started

If something is not clear, I will have to update it.

**Comment by LogGits** [comment]
> I realized I haven't updated to the latest Proton version for this repository. It should be fixed in the latest commit. Before the current version, Proton needed a reference to your plugin (hence this, this).

Ah ok that makes sense.

> > * getSyncManager.broadcast() ? **_<- no sure if there is another one_**
> 
> I'm not sure what getSyncManager is referring to here.

I've been defining the variable as "sync{type}", so it's easier for me to remember (i'm using it to sync stuff in this case). In that usage it's a method to get ProtonManager variable. 

Is `.broadcast()` the correct usage if for instance i need to send the message to specifically the proxy?

> For more detail, you can generally find it on the documentation page: https://proton-1.gitbook.io/proton/getting-started
> 
> If something is not clear, I will have to update it.

Closing because it's pretty much resolved, you are an absolute legend and thanks for clearing all of this up :)

**Comment by mcgrizzz** [comment]
> > I realized I haven't updated to the latest Proton version for this repository. It should be fixed in the latest commit. Before the current version, Proton needed a reference to your plugin (hence this, this).
> 
> Ah ok that makes sense.
> 
> > > * getSyncManager.broadcast() ? **_<- no sure if there is another one_**
> > 
> > 
> > I'm not sure what getSyncManager is referring to here.
> 
> I've been defining the variable as "sync{type}", so it's easier for me to remember (i'm using it to sync stuff in this case). In that usage it's a method to get ProtonManager variable.
> 
> Is `.broadcast()` the correct usage if for instance i need to send the message to specifically the proxy?
> 
> > For more detail, you can generally find it on the documentation page: https://proton-1.gitbook.io/proton/getting-started
> > If something is not clear, I will have to update it.
> 
> Closing because it's pretty much resolved, you are an absolute legend and thanks for clearing all of this up :)

I know this is closed, but I just wanted to reply to your .broadcast() question. 

It is not necessarily correct to use broadcast to send a message to a specific server. In this case, it would be better to send directly to the proxy (unless you have more than one proxy). 

However, it will still work if you only listen for that specific message on the proxy. The only difference is that, if you use broadcast, all your other servers will receive the message and manually filter out the message themselves.
